CREATE TABLE PUSUARIOS (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(150) UNIQUE,
    TELEFONE VARCHAR(20),
    ADMIN BOOLEAN NOT NULL DEFAULT FALSE,
    RECCREATEDON TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PSERVICOS (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO TEXT,
    TEMPOMIN INTEGER NOT NULL CHECK (TEMPOMIN > 0),
    PRECO NUMERIC(10, 2) NOT NULL CHECK (PRECO >= 0),
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE PCONFIGEXP (
    ID SERIAL PRIMARY KEY,
    HORAINICIO TIME NOT NULL DEFAULT TIME '09:00:00',
    HORAFIM TIME NOT NULL DEFAULT TIME '18:00:00',
    CANCELAMENTOMINHORA INTEGER NOT NULL DEFAULT 2
        CHECK (CANCELAMENTOMINHORA >= 0),
    DIASATENDIMENTO INTEGER[] NOT NULL
        DEFAULT ARRAY[1, 2, 3, 4, 5, 6]::INTEGER[],
    CONSTRAINT CHK_HORARIO_CONFIG_VALIDO
        CHECK (HORAFIM > HORAINICIO),
    CONSTRAINT CHK_DIAS_ATENDIMENTO_VALIDOS
        CHECK (DIASATENDIMENTO <@ ARRAY[0, 1, 2, 3, 4, 5, 6]::INTEGER[])
);

CREATE TABLE PAGENDAMENTOS (
    ID SERIAL PRIMARY KEY,
    CLIENTEID INTEGER REFERENCES PUSUARIOS(ID) ON DELETE SET NULL,
    SERVICOID INTEGER NOT NULL REFERENCES PSERVICOS(ID),
    DTINICIO TIMESTAMPTZ NOT NULL,
    DTFIM TIMESTAMPTZ NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'agendado',
    RECCREATEDON TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT CHK_STATUS_AGENDAMENTO
        CHECK (STATUS IN ('agendado', 'cancelado', 'concluido')),

    CONSTRAINT CHK_PERIODO_VALIDO
        CHECK (DTFIM > DTINICIO)
);

CREATE TABLE PBLOQAGENDA (
    ID SERIAL PRIMARY KEY,
    ADMINID INTEGER REFERENCES PUSUARIOS(ID) ON DELETE SET NULL,
    MOTIVO VARCHAR(150) NOT NULL,
    DTINICIO TIMESTAMPTZ NOT NULL,
    DTFIM TIMESTAMPTZ NOT NULL,
    REPDIAUTIL BOOLEAN NOT NULL DEFAULT FALSE,
    RECCREATEDON TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT CHK_BLOQUEIO_VALIDO
        CHECK (DTFIM > DTINICIO)
);
